### ISSUE TITLE
The sign in doesn't work

### ISSUE THREAD

**Issue by afrozegithub** [EuclidStellar/Team-Management-App#1]
Hi @EuclidStellar !

I very much liked your repository. However to make use of it, I am unable to sign in. Can you pls check why?

**Comment by EuclidStellar** [comment]
Thanks for reaching out @afrozegithub  will ping you when the backend server will be started

**Comment by EuclidStellar** [comment]
@afrozegithub hey I have deployed the server again now you can signup and login ans use all services ( make sure to check spam for email verfication mail )

**Comment by afrozegithub** [comment]
@EuclidStellar I think you are talking about the web version? Unfortunately, I couldn't sign in.. the button not workin?

**Comment by EuclidStellar** [comment]
@afrozegithub you're using the app  ryt ?

**Comment by EuclidStellar** [comment]
Hey please schedule a meet preferably according to your time I'll help you to go through the complete process

**Comment by afrozegithub** [comment]
I use this link on the github bio: [hive-trell.vercel.app](https://hive-trell.vercel.app/)

**Comment by EuclidStellar** [comment]
@afrozegithub hey actually web version has very old dependencies that's why it cannot be opened 

You can try an app version of it
